import jsPDF from 'jspdf';

const NAVY = '#0A0F1E';
const TEAL = '#00D4AA';
const MUTED = '#666666';

function wrap(doc, text, x, y, maxWidth, lineHeight = 5.5) {
  const lines = doc.splitTextToSize(String(text || ''), maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

export function downloadPlanPdf(plan) {
  if (!plan) return;
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const margin = 14;
  const colW = W - margin * 2;
  let y = 18;

  // Header
  doc.setFillColor(NAVY);
  doc.rect(0, 0, W, 26, 'F');
  doc.setTextColor('#FFFFFF');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('VitalAI Health Plan', margin, 16);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor('#A0A8B8');
  doc.text(new Date().toLocaleDateString(), margin, 22);

  y = 38;
  doc.setTextColor('#000000');

  // Score block
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(`Health Score: ${plan.healthScore ?? '-'} / 100`, margin, y);
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(`BMI: ${plan.bmi ?? '-'} (${plan.bmiCategory ?? '-'})  |  Daily target: ${plan.dailyCalories ?? '-'} kcal`, margin, y);
  y += 9;

  // Key findings
  doc.setTextColor('#000000');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Key Findings', margin, y); y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  (plan.keyFindings || []).forEach((f) => {
    y = wrap(doc, `• ${f}`, margin, y, colW);
    y += 1;
  });
  y += 2;

  // Blood markers
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Blood Markers', margin, y); y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Marker', margin, y);
  doc.text('Value', margin + 70, y);
  doc.text('Range', margin + 110, y);
  doc.text('Status', margin + 155, y);
  y += 4;
  doc.setDrawColor(200);
  doc.line(margin, y, margin + colW, y);
  y += 4;
  doc.setFont('helvetica', 'normal');
  (plan.bloodMarkers || []).forEach((m) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(String(m.name || ''), margin, y, { maxWidth: 68 });
    doc.text(String(m.value || ''), margin + 70, y);
    doc.text(String(m.normalRange || ''), margin + 110, y);
    doc.setTextColor(TEAL);
    doc.text(String(m.status || ''), margin + 155, y);
    doc.setTextColor('#000000');
    y += 6;
  });
  y += 4;

  // Diet
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Diet Plan', margin, y); y += 6;
  doc.setFontSize(10);
  const diet = plan.dietPlan || {};
  [['Breakfast', 'breakfast'], ['Mid-Morning Snack', 'morningSnack'], ['Lunch', 'lunch'], ['Evening Snack', 'eveningSnack'], ['Dinner', 'dinner']].forEach(([label, key]) => {
    const m = diet[key];
    if (!m) return;
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}: ${m.name || '-'} ${m.calories ? `(${m.calories} kcal)` : ''}`, margin, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    if (m.description) y = wrap(doc, m.description, margin, y, colW);
    y += 2;
  });

  // Exercise
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Exercise Plan', margin, y); y += 6;
  doc.setFontSize(10);
  const ex = plan.exercisePlan || {};
  ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'].forEach((d) => {
    const day = ex[d];
    if (!day) return;
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.text(`${d.charAt(0).toUpperCase()+d.slice(1)} — ${day.type || '-'} (${day.duration || '-'})`, margin, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    y = wrap(doc, day.exercises || '-', margin, y, colW);
    y += 2;
  });

  // Disclaimer
  if (y > 260) { doc.addPage(); y = 20; }
  y += 4;
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  y = wrap(doc, 'Medical disclaimer: This plan is generated by AI and is for informational purposes only. It is not medical advice. Always consult a qualified healthcare provider before making changes to your treatment, medication, or lifestyle.', margin, y, colW, 4.5);

  doc.save(`VitalAI-Plan-${new Date().toISOString().slice(0, 10)}.pdf`);
}
