import React, { useState } from 'react';
import BloodReport from './BloodReport.jsx';
import DietPlan from './DietPlan.jsx';
import ExercisePlan from './ExercisePlan.jsx';
import { downloadPlanPdf } from '../pdfExport.js';

const ALL_TABS = [
  { key: 'blood', label: 'Blood Report', icon: '🩸' },
  { key: 'diet',  label: 'Diet Plan',    icon: '🥗' },
  { key: 'exercise', label: 'Exercise Plan', icon: '💪' },
];

export default function ResultDashboard({ data, onReset, hideBloodTab = false }) {
  const tabs = hideBloodTab ? ALL_TABS.filter((t) => t.key !== 'blood') : ALL_TABS;
  const [tab, setTab] = useState(tabs[0].key);

  return (
    <section className="animate-fade-in">
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3 sm:gap-4 mb-5 sm:mb-6">
        <div>
          <h2 className="text-2xl sm:text-3xl font-bold">Your personalized plan</h2>
          <p className="text-white/60 mt-1 text-sm sm:text-base">Generated by AI from your report and profile.</p>
        </div>
        <div className="flex gap-2 w-full sm:w-auto">
          <button onClick={() => downloadPlanPdf(data)} className="btn-ghost flex-1 sm:flex-none text-sm">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
            Download PDF
          </button>
          <button onClick={onReset} className="btn-primary flex-1 sm:flex-none text-sm">Start over</button>
        </div>
      </div>

      {hideBloodTab && (
        <div className="card p-4 mb-6 bg-teal/5 border-teal/30 text-sm text-white/80">
          <span className="font-semibold text-teal">Quick Plan</span> · this plan is based on your BMI and goals.
          For a more accurate analysis, <button onClick={onReset} className="underline text-teal hover:text-teal-light">upload a blood report</button>.
        </div>
      )}

      <div className="flex gap-1.5 sm:gap-2 p-1 bg-navy-100/50 border border-white/10 rounded-2xl mb-5 sm:mb-6 overflow-x-auto scrollbar-thin">
        {tabs.map((t) => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className={`flex-1 min-w-fit px-3 sm:px-4 py-2 sm:py-2.5 rounded-xl text-xs sm:text-sm font-medium transition whitespace-nowrap
              ${tab === t.key ? 'bg-teal text-navy-900 shadow-glow' : 'text-white/70 hover:bg-white/5'}`}
            aria-selected={tab === t.key}
            role="tab"
          >
            <span className="mr-1 sm:mr-1.5">{t.icon}</span>{t.label}
          </button>
        ))}
      </div>

      <div className="animate-fade-in">
        {tab === 'blood'    && <BloodReport data={data} />}
        {tab === 'diet'     && <DietPlan data={data} />}
        {tab === 'exercise' && <ExercisePlan data={data} />}
      </div>
    </section>
  );
}
